In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('heart.csv')

In [3]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [4]:
df['restecg'].unique()

array([1, 0, 2])

age,
sex,
chest pain type (4 values),
resting blood pressure,
serum cholestoral in mg/dl,
fasting blood sugar > 120 mg/dl,
resting electrocardiographic results (values 0,1,2),
maximum heart rate achieved,
exercise induced angina,
oldpeak = ST depression induced by exercise relative to rest,
the slope of the peak exercise ST segment,
number of major vessels (0-3) colored by flourosopy,
thal: 0 = normal; 1 = fixed defect; 2 = reversable defect,

In [5]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [6]:
print(df['cp'].unique())
print(df['sex'].unique())
print(df['trestbps'].unique())
print(df['thal'].unique())
print(df['oldpeak'].unique())
print(df['slope'].unique())

[0 1 2 3]
[1 0]
[125 140 145 148 138 100 114 160 120 122 112 132 118 128 124 106 104 135
 130 136 180 129 150 178 146 117 152 154 170 134 174 144 108 123 110 142
 126 192 115  94 200 165 102 105 155 172 164 156 101]
[3 2 1 0]
[1.  3.1 2.6 0.  1.9 4.4 0.8 3.2 1.6 3.  0.7 4.2 1.5 2.2 1.1 0.3 0.4 0.6
 3.4 2.8 1.2 2.9 3.6 1.4 0.2 2.  5.6 0.9 1.8 6.2 4.  2.5 0.5 0.1 2.1 2.4
 3.8 2.3 1.3 3.5]
[2 0 1]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [8]:
# getting all different types of features
num_features=[feature for feature in df.columns if df[feature].dtype!='O']
print("Num of numerical feature: ",len(num_features))
cat_features= [ feature  for feature in df.columns if df[feature].dtype=='O']
print("Num of categorical features is: ",len(cat_features))
discrete_feature=[feature for feature in num_features if len(df[feature].unique())<=25]
print("Num of discrete features are: ",len(discrete_feature))
continious_feature=[feature for feature in num_features if feature not in discrete_feature]
print("Num of continious feature are: ",len(continious_feature))

Num of numerical feature:  14
Num of categorical features is:  0
Num of discrete features are:  9
Num of continious feature are:  5

In [9]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [10]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [11]:
x=df.drop(columns=['target'])
y=df['target']
from sklearn.model_selection import train_test_split

In [12]:
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
x_train.shape,x_test.shape

((820, 13), (205, 13))

In [14]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [15]:
def evaluate_model(true, predicted):
    acc = accuracy_score(true, predicted)
    return acc

In [16]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Ridge": RidgeClassifier(),
    "K-Neighbors Classifier": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier()
}

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train)

    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # Evaluation
    train_acc = accuracy_score(y_train, y_train_pred)
    test_acc = accuracy_score(y_test, y_test_pred)

    print(list(models.keys())[i])

    print('Model performance for Training set')
    print(f"- Accuracy: {train_acc:.4f}")
    print("Confusion Matrix:\n", confusion_matrix(y_train, y_train_pred))
    print("Classification Report:\n", classification_report(y_train, y_train_pred))

    print('----------------------------------')

    print('Model performance for Test set')
    print(f"- Accuracy: {test_acc:.4f}")
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
    print("Classification Report:\n", classification_report(y_test, y_test_pred))

    print('='*35)
    print('\n')

C:\Users\Harshita\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression
Model performance for Training set
- Accuracy: 0.8659
Confusion Matrix:
 [[324  73]
 [ 37 386]]
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.82      0.85       397
           1       0.84      0.91      0.88       423

    accuracy                           0.87       820
   macro avg       0.87      0.86      0.87       820
weighted avg       0.87      0.87      0.87       820

----------------------------------
Model performance for Test set
- Accuracy: 0.7854
Confusion Matrix:
 [[71 31]
 [13 90]]
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.70      0.76       102
           1       0.74      0.87      0.80       103

    accuracy                           0.79       205
   macro avg       0.79      0.78      0.78       205
weighted avg       0.79      0.79      0.78       205

===================================


Ridge
Model performance for Training set
- Accuracy: 0.8573
Confusion Matrix:
 [[307  90]
 [ 27 396]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.77      0.84       397
           1       0.81      0.94      0.87       423

    accuracy                           0.86       820
   macro avg       0.87      0.85      0.86       820
weighted avg       0.87      0.86      0.86       820

----------------------------------
Model performance for Test set
- Accuracy: 0.8098
Confusion Matrix:
 [[70 32]
 [ 7 96]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.69      0.78       102
           1       0.75      0.93      0.83       103

    accuracy                           0.81       205
   macro avg       0.83      0.81      0.81       205
weighted avg       0.83      0.81      0.81       205

===================================


K-Neighbors Classifier
Model performance for Training set
- Accuracy: 0.9232
Confusion Matrix:
 [[371  26]
 [ 37 386]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.93      0.92       397
           1       0.94      0.91      0.92       423

    accuracy                           0.92       820
   macro avg       0.92      0.92      0.92       820
weighted avg       0.92      0.92      0.92       820

----------------------------------
Model performance for Test set
- Accuracy: 0.7317
Confusion Matrix:
 [[74 28]
 [27 76]]
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.73      0.73       102
           1       0.73      0.74      0.73       103

    accuracy                           0.73       205
   macro avg       0.73      0.73      0.73       205
weighted avg       0.73      0.73      0.73       205

===================================


Decision Tree
Model performance for Training set
- Accuracy: 1.0000
Confusion Matrix:
 [[397   0]
 [  0 423]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       397
           1       1.00      1.00      1.00       423

    accuracy                           1.00       820
   macro avg       1.00      1.00      1.00       820
weighted avg       1.00      1.00      1.00       820

----------------------------------
Model performance for Test set
- Accuracy: 0.9854
Confusion Matrix:
 [[102   0]
 [  3 100]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.97      0.99       103

    accuracy                           0.99       205
   macro avg       0.99      0.99      0.99       205
weighted avg       0.99      0.99      0.99       205

===================================


Random Forest
Model performance for Training set
- Accuracy: 1.0000
Confusion Matrix:
 [[397   0]
 [  0 423]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       397
           1       1.00      1.00      1.00       423

    accuracy                           1.00       820
   macro avg       1.00      1.00      1.00       820
weighted avg       1.00      1.00      1.00       820

----------------------------------
Model performance for Test set
- Accuracy: 0.9854
Confusion Matrix:
 [[102   0]
 [  3 100]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.97      0.99       103

    accuracy                           0.99       205
   macro avg       0.99      0.99      0.99       205
weighted avg       0.99      0.99      0.99       205

===================================


AdaBoost
Model performance for Training set
- Accuracy: 0.9049
Confusion Matrix:
 [[350  47]
 [ 31 392]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.88      0.90       397
           1       0.89      0.93      0.91       423

    accuracy                           0.90       820
   macro avg       0.91      0.90      0.90       820
weighted avg       0.91      0.90      0.90       820

----------------------------------
Model performance for Test set
- Accuracy: 0.8146
Confusion Matrix:
 [[79 23]
 [15 88]]
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.77      0.81       102
           1       0.79      0.85      0.82       103

    accuracy                           0.81       205
   macro avg       0.82      0.81      0.81       205
weighted avg       0.82      0.81      0.81       205

===================================

In [18]:
decision_tree_params={ 'criterion': ['gini', 'entropy', 'log_loss'],
    'splitter': ['best', 'random'],
    'max_depth': [None, 3, 5, 7, 10, 15, 20],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 4, 10],
    'max_features': [None, 'sqrt', 'log2'],
    'class_weight': [None, 'balanced']}

rf_params = {
    'n_estimators': [100, 200, 300, 500, 800],
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None, 5, 10, 20, 30],
    'min_samples_split': [2, 5, 10, 15],
    'min_samples_leaf': [1, 2, 4, 6],
    'max_features': ['sqrt', 'log2', None],
    'bootstrap': [True, False],
    'class_weight': [None, 'balanced']
}

In [19]:
randomcv_model=[('RandomForest',RandomForestClassifier(),rf_params),
                ('DecisionTree',DecisionTreeClassifier(),decision_tree_params)]

In [20]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_model:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
    random.fit(x_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
---------------- Best Params for RandomForest -------------------
{'n_estimators': 300, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 10, 'criterion': 'log_loss', 'class_weight': None, 'bootstrap': False}
---------------- Best Params for DecisionTree -------------------
{'splitter': 'random', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': None, 'criterion': 'entropy', 'class_weight': None}

In [21]:
model=RandomForestClassifier(n_estimators=100, min_samples_split= 5, min_samples_leaf= 1, max_features= 'sqrt', max_depth= None, criterion= 'log_loss', class_weight=None, bootstrap= False)

In [22]:
model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=False, criterion='log_loss',
                       min_samples_split=5)

In [23]:
y_train_pred=model.predict(x_train)
y_test_pred=model.predict(x_test)

In [24]:
score= accuracy_score(y_test,y_test_pred)
print(score)
cm=confusion_matrix(y_test,y_test_pred)
print(cm)
cr=classification_report(y_test,y_test_pred)
print(cr)

0.9853658536585366
[[102   0]
 [  3 100]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.97      0.99       103

    accuracy                           0.99       205
   macro avg       0.99      0.99      0.99       205
weighted avg       0.99      0.99      0.99       205

In [25]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [26]:
import pickle  
pickle.dump(model,open('heart_model.pkl','wb'))